version: '3.7'

services:
  jobmanager:
    image: flink:1.9.0-scala_2.12
    ports:
      - "18081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.9.0-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.2
    restart: always
    ports:
      - '9200:9200'     #java、集群通信端口
      - '9300:9300'     #http通信端口
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    privileged: true    #环境变量
    volumes:
      - type: bind
        source: ./external_config/elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml


  elasticsearch1:
    container_name: elasticsearch1
    image: elasticsearch:7.6.2
    restart: always
    ports:
      - '9201:9200'     #java、集群通信端口
      - '9301:9300'     #http通信端口
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    privileged: true    #环境变量
    volumes:
      - type: bind
        source: ./external_config/elasticsearch/elasticsearch1.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml

  elasticsearch2:
    container_name: elasticsearch2
    image: elasticsearch:7.6.2
    restart: always
    ports:
      - '9202:9200'     #java、集群通信端口
      - '9302:9300'     #http通信端口
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    privileged: true    #环境变量
    volumes:
      - type: bind
        source: ./external_config/elasticsearch/elasticsearch2.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    container_name: kibana
    image: kibana:7.6.2
    restart: always
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  kibana1:
    container_name: kibana1
    image: kibana:7.6.2
    ports:
      - "5602:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://host.docker.internal:19200

  oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    container_name: skywalking-oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 11800:11800
      - 12800:12800
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
#    volumes:
#      - type: bind
#        source: ./external_config/skyWalking/application.yml
#        target: /skywalking/config/application.yml


  ui:
    image: apache/skywalking-ui:8.3.0
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 8082:8080
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: oap:12800


  redis:
    image: redis:alpine
    container_name: redis1
    restart: always
    ports:
      - 6380:6379
